[package]
name = "bytetrack-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
ndarray = { version = "*", default-features = false }
ndarray-linalg = { version = "0.16", features = ["openblas-static"] }
num = { varsion = "*" }


[dev-dependencies]
nearly_eq = "0.2.4"