[package]
name = "bytetrack-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
nalgebra = "*"
num = "*"


[dev-dependencies]
nearly_eq = "0.2.4"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
quickcheck = "1.0.3"
rand = "0.8.5"
